# Project information
site_name: ğŸ§­ aiogram 3.x æŒ‡å—
site_description: ä½¿ç”¨ aiogram 3.x æ¡†æ¶ç”¨ Python ä¸º Telegram å¼€å‘æœºå™¨äººçš„æ•™ç¨‹ã€‚
site_author: MasterGroosha
site_url: https://mastergroosha.github.io/aiogram-3-guide
docs_dir: book_src
site_dir: docs

# Repository
repo_name: Donald996/aiogram-3-guide
repo_url: https://github.com/Donald996/aiogram-3-guide
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023-2024 SychO

# Configuration
theme:
  name: material
  custom_dir: book_src/overrides
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot
#  features:
#    - navigation.expand

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/SychO6
      name: "Telegram"
    - icon: fontawesome/brands/github
      link: https://github.com/Donald996/aiogram-3-guide
      name: GitHub

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 'å¯¼è¨€': index.md
  - 'äº†è§£aiogram': quickstart.md
  - 'å¤„ç†ä¿¡æ¯': messages.md
  - 'æŒ‰é’®': buttons.md
  - 'è·¯ç”±å™¨': routers.md
  - 'è¿‡æ»¤ç¨‹åºå’Œä¸­é—´ä»¶': filters-and-middlewares.md
  - 'æ›´æ–°': special-updates.md
  - 'æœ‰é™çŠ¶æ€æœº': fsm.md
  - 'å†…è”æ¨¡å¼': inline-mode.md
#  - 'ğŸ”’ é«˜çº§': advanced-teaser.md
#  - 'Ğ”Ğ¾Ğ¿Ğ¾Ğ»Ğ½Ğ¸Ñ‚ĞµĞ»ÑŒĞ½Ğ¾Ğµ Ñ‡Ñ‚ĞµĞ½Ğ¸Ğµ':
#    - 'Ğ¢ĞµÑÑ‚': extra/test.md


plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      video_type: mp4
      css_style:
        width: "100%"
        height: "100%"
  - search:
      lang:
        - en
        - zh


# Custom
#nav_name: "ç›®å½•"
