# Project information
site_name: –ü–∏—à–µ–º Telegram-–±–æ—Ç–æ–≤ —Å aiogram 3.x
site_description: –£—á–µ–±–Ω–∏–∫ –ø–æ —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–µ –±–æ—Ç–æ–≤ –¥–ª—è Telegram –Ω–∞ —è–∑—ã–∫–µ Python –ø—Ä–∏ –ø–æ–º–æ—â–∏ —Ñ—Ä–µ–π–º–≤–æ—Ä–∫–∞ aiogram 3.x
site_author: MasterGroosha
site_url: https://mastergroosha.github.io/aiogram-3-guide
docs_dir: book_src
site_dir: docs

# Repository
repo_name: MasterGroosha/aiogram-3-guide
repo_url: https://github.com/MasterGroosha/aiogram-3-guide
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020-2024 Groosha

# Configuration
theme:
  name: material
  custom_dir: book_src/overrides
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: –í–∫–ª—é—á–∏—Ç—å —Ç—ë–º–Ω—É—é —Ç–µ–º—É
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: –í–∫–ª—é—á–∏—Ç—å —Å–≤–µ—Ç–ª—É—é —Ç–µ–º—É
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot
#  features:
#    - navigation.expand

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+DE0_2nCvbXozZjUy
      name: "–ß–∞—Ç –≤ Telegram"
    - icon: fontawesome/brands/github
      link: https://github.com/MasterGroosha/aiogram-3-guide
      name: GitHub
  announcement: –ö–∞–∂–µ—Ç—Å—è —ç—Ç–∞ —Å—Ç—Ä–∞–Ω–∏—Ü–∞ –Ω–µ –±—ã–ª–∞ –ø–µ—Ä–µ–≤–µ–¥–µ–Ω–∞ –Ω–∞ —ç—Ç–æ—Ç –Ø–∑—ã–∫ –∏ –ø—Ä–µ–¥–≤–∞—Ä–∏—Ç–µ–ª—å–Ω–æ –±—É–¥–µ—Ç –ø–æ–∫–∞–∑–∞–Ω–∞ –Ω–∞ –†—É—Å—Å–∫–æ–º –Ø–∑—ã–∫–µ.
  translation_warning_string: –í–∞–∂–Ω–æ–µ –ø—Ä–µ–¥—É–ø—Ä–µ–∂–¥–µ–Ω–∏–µ –æ –ø–µ—Ä–µ–≤–æ–¥–µ!
  translation_in_work_string: |
    –ü—Ä–∏–≤–µ—Ç! –≠—Ç–æ —Å–æ–æ–±—â–µ–Ω–∏–µ –æ—Ç –ø–µ—Ä–µ–≤–æ–¥—á–∏–∫–∞ <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>.
    –ü–æ–∂–∞–ª—É–π—Å—Ç–∞, –∏–º–µ–π—Ç–µ –≤ –≤–∏–¥—É, —á—Ç–æ —ç—Ç–∞ —Å—Ç—Ä–∞–Ω–∏—Ü–∞ –≤—Å–µ –µ—â–µ –ø–µ—Ä–µ–≤–æ–¥–∏—Ç—Å—è.
  translation_stopped_string: |
    –ü—Ä–∏–≤–µ—Ç! –≠—Ç–æ —Å–æ–æ–±—â–µ–Ω–∏–µ –æ—Ç –ø–µ—Ä–µ–≤–æ–¥—á–∏–∫–∞ <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>.
    –ü–µ—Ä–µ–≤–æ–¥ —ç—Ç–æ–π —Å—Ç—Ä–∞–Ω–∏—Ü—ã –æ—Å—Ç–∞–Ω–æ–≤–ª–µ–Ω.
    

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.blocks.details
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - '–í–≤–µ–¥–µ–Ω–∏–µ': index.md
  - '–ó–Ω–∞–∫–æ–º—Å—Ç–≤–æ —Å aiogram': quickstart.md
  - '–†–∞–±–æ—Ç–∞ —Å —Å–æ–æ–±—â–µ–Ω–∏—è–º–∏': messages.md
  - '–ö–Ω–æ–ø–∫–∏': buttons.md
  - '–†–æ—É—Ç–µ—Ä—ã. –°—Ç—Ä—É–∫—Ç—É—Ä–∞': routers.md
  - '–§–∏–ª—å—Ç—Ä—ã –∏ –º–∏–¥–ª–≤–∞—Ä–∏': filters-and-middlewares.md
  - '–û—Å–æ–±—ã–µ –∞–ø–¥–µ–π—Ç—ã': special-updates.md
  - '–ö–æ–Ω–µ—á–Ω—ã–µ –∞–≤—Ç–æ–º–∞—Ç—ã': fsm.md
  - '–ò–Ω–ª–∞–π–Ω-—Ä–µ–∂–∏–º': inline-mode.md
  - '–ü–ª–∞—Ç–µ–∂–∏': payments.md
  - 'üîí –ü—Ä–æ–¥–≤–∏–Ω—É—Ç—ã–π —É—Ä–æ–≤–µ–Ω—å': advanced-teaser.md
#  - '–î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ–µ —á—Ç–µ–Ω–∏–µ':
#    - '–¢–µ—Å—Ç': extra/test.md


plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      video_type: mp4
      css_style:
        width: "100%"
        height: "100%"
  - search:
      lang:
        - en
        - ru
  - i18n:
      reconfigure_material: true
      reconfigure_search: true
      docs_structure: folder
      languages:
        - locale: ru
          name: –†—É—Å—Å–∫–∏–π
          default: true
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            '–í–≤–µ–¥–µ–Ω–∏–µ': "Introduction"
            '–ó–Ω–∞–∫–æ–º—Å—Ç–≤–æ —Å aiogram': "Getting Started with aiogram"
            '–†–∞–±–æ—Ç–∞ —Å —Å–æ–æ–±—â–µ–Ω–∏—è–º–∏': "Working with Messages"
            '–ö–Ω–æ–ø–∫–∏': "Buttons"
            '–†–æ—É—Ç–µ—Ä—ã. –°—Ç—Ä—É–∫—Ç—É—Ä–∞': "Routers. Structure"
            '–§–∏–ª—å—Ç—Ä—ã –∏ –º–∏–¥–ª–≤–∞—Ä–∏': "Filters and Middlewares"
            '–û—Å–æ–±—ã–µ –∞–ø–¥–µ–π—Ç—ã': "Special Updates"
            '–ö–æ–Ω–µ—á–Ω—ã–µ –∞–≤—Ç–æ–º–∞—Ç—ã': "Finite State Machines"
            '–ò–Ω–ª–∞–π–Ω-—Ä–µ–∂–∏–º': "Inline Mode"
            '–ü–ª–∞—Ç–µ–∂–∏': "Payments"
            'üîí –ü—Ä–æ–¥–≤–∏–Ω—É—Ç—ã–π —É—Ä–æ–≤–µ–Ω—å': "üîí Advanced Level"
          nav_name: "Contents"
          site_name: Writing Telegram Bots with aiogram 3.x
          site_description: A tutorial on developing bots for Telegram using the aiogram 3.x framework in Python
          theme:
            name: material
            custom_dir: book_src/overrides
            language: en
            palette:
              - media: "(prefers-color-scheme: light)"
                scheme: default
                primary: purple
                toggle:
                  icon: material/brightness-4
                  name: Switch to Dark Theme
              - media: "(prefers-color-scheme: dark)"
                scheme: slate
                primary: purple
                toggle:
                  icon: material/brightness-7
                  name: Switch to Light Theme
            font:
              text: Roboto
              code: Roboto Mono
            icon:
              logo: material/robot
          extra:
            social:
              - icon: fontawesome/brands/telegram
                link: https://t.me/+DE0_2nCvbXozZjUy
                name: "Chat in Telegram"
              - icon: fontawesome/brands/github
                link: https://github.com/MasterGroosha/aiogram-3-guide
                name: GitHub
            announcement: It seems this page has not been translated into this Language and will preliminarily be displayed in Russian.
            translation_warning_string: An important warning about translation!
            translation_in_work_string: |
              Hello! This message is from the translator <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>.
              Please keep in mind that this page is still being translated.
            translation_stopped_string: |
              Hello! This message is from the translator <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>.
              Translation of this page has been stopped.
        - locale: uk
          name: –£–∫—Ä–∞—ó–Ω—Å—å–∫–∞
          build: false
          nav_translations:
            '–í–≤–µ–¥–µ–Ω–∏–µ': "–í—Å—Ç—É–ø"
            '–ó–Ω–∞–∫–æ–º—Å—Ç–≤–æ —Å aiogram': "–ó–Ω–∞–π–æ–º—Å—Ç–≤–æ –∑ aiogram"
            '–†–∞–±–æ—Ç–∞ —Å —Å–æ–æ–±—â–µ–Ω–∏—è–º–∏': "–†–æ–±–æ—Ç–∞ –∑ –ø–æ–≤—ñ–¥–æ–º–ª–µ–Ω–Ω—è–º–∏"
            '–ö–Ω–æ–ø–∫–∏': "–ö–Ω–æ–ø–∫–∏"
            '–†–æ—É—Ç–µ—Ä—ã. –°—Ç—Ä—É–∫—Ç—É—Ä–∞': "–†–æ—É—Ç–µ—Ä–∏. –°—Ç—Ä—É–∫—Ç—É—Ä–∞"
            '–§–∏–ª—å—Ç—Ä—ã –∏ –º–∏–¥–ª–≤–∞—Ä–∏': "–§—ñ–ª—å—Ç—Ä–∏ —Ç–∞ –º—ñ–¥–ª–≤–∞—Ä–∏"
            '–û—Å–æ–±—ã–µ –∞–ø–¥–µ–π—Ç—ã': "–û—Å–æ–±–ª–∏–≤—ñ –æ–Ω–æ–≤–ª–µ–Ω–Ω—è"
            '–ö–æ–Ω–µ—á–Ω—ã–µ –∞–≤—Ç–æ–º–∞—Ç—ã': "–ö—ñ–Ω—Ü–µ–≤—ñ –∞–≤—Ç–æ–º–∞—Ç–∏"
            '–ò–Ω–ª–∞–π–Ω-—Ä–µ–∂–∏–º': "–Ü–Ω–ª–∞–π–Ω-—Ä–µ–∂–∏–º"
            '–ü–ª–∞—Ç–µ–∂–∏': "–ü–ª–∞—Ç–µ–∂—ñ"
            'üîí –ü—Ä–æ–¥–≤–∏–Ω—É—Ç—ã–π —É—Ä–æ–≤–µ–Ω—å': "üîí –ü—Ä–æ—Å—É–Ω—É—Ç–∏–π —Ä—ñ–≤–µ–Ω—å"
          nav_name: "–ó–º—ñ—Å—Ç"
          site_name: –ù–∞–ø–∏—Å–∞–Ω–Ω—è –±–æ—Ç—ñ–≤ –¥–ª—è Telegram –∑ aiogram 3.x
          site_description: –ü–æ—Å—ñ–±–Ω–∏–∫ –∑ —Ä–æ–∑—Ä–æ–±–∫–∏ –±–æ—Ç—ñ–≤ –¥–ª—è Telegram –∑–∞ –¥–æ–ø–æ–º–æ–≥–æ—é —Ñ—Ä–µ–π–º–≤–æ—Ä–∫—É aiogram 3.x –Ω–∞ Python
          theme:
            name: material
            custom_dir: book_src/overrides
            language: uk
            palette:
              - media: "(prefers-color-scheme: light)"
                scheme: default
                primary: purple
                toggle:
                  icon: material/brightness-4
                  name: –ü–µ—Ä–µ–º–∫–Ω—É—Ç–∏ –Ω–∞ —Ç–µ–º–Ω—É —Ç–µ–º—É
              - media: "(prefers-color-scheme: dark)"
                scheme: slate
                primary: purple
                toggle:
                  icon: material/brightness-7
                  name: –ü–µ—Ä–µ–º–∫–Ω—É—Ç–∏ –Ω–∞ —Å–≤—ñ—Ç–ª—É —Ç–µ–º—É
            font:
              text: Roboto
              code: Roboto Mono
            icon:
              logo: material/robot
          extra:
            social:
              - icon: fontawesome/brands/telegram
                link: https://t.me/+DE0_2nCvbXozZjUy
                name: "–ß–∞—Ç —É Telegram"
              - icon: fontawesome/brands/github
                link: https://github.com/MasterGroosha/aiogram-3-guide
                name: GitHub
            announcement: –ó–¥–∞—î—Ç—å—Å—è, —Ü—è —Å—Ç–æ—Ä—ñ–Ω–∫–∞ —â–µ –Ω–µ –ø–µ—Ä–µ–∫–ª–∞–¥–µ–Ω–∞ –Ω–∞ —Ü—é –º–æ–≤—É —ñ –ø–æ–ø–µ—Ä–µ–¥–Ω—å–æ –±—É–¥–µ –≤—ñ–¥–æ–±—Ä–∞–∂–µ–Ω–∞ —Ä–æ—Å—ñ–π—Å—å–∫–æ—é.
            translation_warning_string: –í–∞–∂–ª–∏–≤–µ –ø–æ–ø–µ—Ä–µ–¥–∂–µ–Ω–Ω—è –ø—Ä–æ –ø–µ—Ä–µ–∫–ª–∞–¥!
            translation_in_work_string: |
              –ü—Ä–∏–≤—ñ—Ç! –¶–µ –ø–æ–≤—ñ–¥–æ–º–ª–µ–Ω–Ω—è –≤—ñ–¥ –ø–µ—Ä–µ–∫–ª–∞–¥–∞—á–∞ <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>.
              –ë—É–¥—å –ª–∞—Å–∫–∞, –º–∞–π—Ç–µ –Ω–∞ —É–≤–∞–∑—ñ, —â–æ —Ü—è —Å—Ç–æ—Ä—ñ–Ω–∫–∞ —â–µ –ø–µ—Ä–µ–∫–ª–∞–¥–∞—î—Ç—å—Å—è.
            translation_stopped_string: |
              –ü—Ä–∏–≤—ñ—Ç! –¶–µ –ø–æ–≤—ñ–¥–æ–º–ª–µ–Ω–Ω—è –≤—ñ–¥ –ø–µ—Ä–µ–∫–ª–∞–¥–∞—á–∞ <a href="https://github.com/Vadim-Khristenko">VAI || Programmer</a>.
              –ü–µ—Ä–µ–∫–ª–∞–¥ —Ü—ñ—î—ó —Å—Ç–æ—Ä—ñ–Ω–∫–∏ –∑—É–ø–∏–Ω–µ–Ω–æ.


# Custom
nav_name: "–û–≥–ª–∞–≤–ª–µ–Ω–∏–µ"
